"""Contracts for model-proposed and runtime-executed tool actions.

M01: Defines vocab only.

M03 will implement:
    - registry
    - schema validation
    - authorization
    - approval
    - execution
    - timeout handling
    - receipts
    - error normalization
"""

from enum import StrEnum
from typing import Literal, Self

from pydantic import Field, JsonValue, model_validator

from pocketagent.runtime.contracts.base import ContractModel
from pocketagent.runtime.contracts.common import NonEmptyStr

class ToolDefinition(ContractModel):
    """Model-visible description of one tool capability.
    
    M02: ModelRequest will expose them to model.
    M03: ToolRegistry will produce these definition.
    """
    
    name: NonEmptyStr
    description: str # tool description
    
    # Provider-neutral JSON Schema representation
    input_schema: dict[str, JsonValue] = Field(default_factory=dict)

class ToolCallProposal(ContractModel):
    """Model's request to use a tool.
    
    SECURITY RULE:
    The object means only "model WANTS this action"
    
    It does NOT mean: authorized / approved / executed / successful
    """
    
    kind: Literal["tool_call"] = "tool_call" # Discriminator - only hold this value
    
    call_id: NonEmptyStr
    tool_name: NonEmptyStr
    
    arguments: dict[str, JsonValue] = Field(default_factory=dict)

class ToolCallStatus(StrEnum):
    """Runtime lifecycle of a proposed tool call."""
    
    PROPOSED = "PROPOSED"
    REJECTED = "REJECTED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"
    
class ToolResult(ContractModel):
    """Successful result returned by deterministic tool execution.
    Model only generates ToolProposal.
    Model never generates ToolResult.
    
    M03 creates these.
    M04 exposes selected results to model.
    M05 persist reference for replay safety.
    """
    
    call_id: NonEmptyStr # to map to Proposal
    
    output: JsonValue | None = None
    
    latency_ms: int | None = None
    
    receipt_id: NonEmptyStr | None = None # uuid by external system. proof of receipt of results.
    idempotency_key: NonEmptyStr | None = None # generated by ToolExecutor in the runtime.

class ToolError(ContractModel):
    """Normalized tool failure.
    
    ToolFailure should not throw exception.
    It should be normalized and return to model for further reasoning.
    """
    
    call_id: NonEmptyStr # map to ToolCallProposal / ToolResult
    
    code: NonEmptyStr # Machine-Readable cateogory (e.g. TABLE_NOT_FOUND)
    message: str # error message for human
    
    retryable: bool = False # to prevent agent trap in infinite loop.
    # True: network / 503 service unavail / rate limit hit errors - make sense to retry
    # False: File not found, permission denied, invalid argument, syntax error - retrying yields same result
    
    details: dict[str, JsonValue] = Field(default_factory=dict) # different tools, different payload. Flexible storage.

class ToolCallRecord(ContractModel):
    """Authoritative runtime record of one tool-call lifecycle.
    
    RuntimeState stores records, not merely data contracts.
    ToolCallRecord updates over time, based on what was executed within tool-call lifecycle.
    
    This lets the runtime know:
        - what was requested (ToolCallProposal)
        - whether it ran (ToolCallStatus)
        - whether it failed (ToolError)
        - what result / receipt it produced (ToolResult)
    """
    
    proposal: ToolCallProposal
    
    status: ToolCallStatus = ToolCallStatus.PROPOSED
    
    attempt: int = Field(default=1, ge=1)
    
    result: ToolResult | None = None
    error: ToolError | None = None
    
    @model_validator(mode="after") # check multiple fields validity after creation of ToolCallRecord obj.
    def validate_result_and_error(self) -> Self:
        """Keep tool lifecycle records internally consistent"""
        if self.result is not None and self.error is not None:
            raise ValueError("ToolCallRecord cannot contain both result and error.")
        
        if self.result is not None:
            if self.result.call_id != self.proposal.call_id:
                raise ValueError("ToolResult.call_id must match proposal.call_id.")
        
        if self.error is not None:
            if self.error.call_id != self.proposal.call_id:
                raise ValueError("ToolError.call_id must match proposal.call_id.")
        
        if self.status is ToolCallStatus.SUCCEEDED:
            if self.result is None:
                raise ValueError("SUCCEEDED tool call must contain ToolResult.")
        
        if self.status is ToolCallStatus.FAILED:
            if self.error is None:
                raise ValueError("FAILED tool call must contain ToolError.")
        
        return self
    
    
    